# Generated by Django 3.1.5 on 2021-01-09 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(0, 'tech'), (1, 'product'), (2, 'operation'), (3, 'design')], verbose_name='job_type')),
                ('job_name', models.CharField(max_length=250, verbose_name='job_name')),
                ('job_city', models.SmallIntegerField(choices=[(0, 'Taipei'), (1, 'Tai'), (2, 'Tau')], verbose_name='job_city')),
                ('job_responsibility', models.TextField(max_length=1024, verbose_name='job_responsibility')),
                ('job_requirement', models.TextField(max_length=1024, verbose_name='job_requirement')),
                ('created_date', models.DateTimeField(verbose_name='created_date')),
                ('modified_date', models.DateTimeField(verbose_name='modify_date')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
    ]
