# Generated by Django 3.1.5 on 2021-01-17 15:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_auto_20210112_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=135, verbose_name='姓名')),
                ('city', models.CharField(max_length=135, verbose_name='城市')),
                ('phone', models.CharField(max_length=135, verbose_name='手機號碼')),
                ('email', models.EmailField(blank=True, max_length=135, verbose_name='郵箱')),
                ('apply_position', models.CharField(blank=True, max_length=135, verbose_name='應徵職位')),
                ('born_address', models.CharField(blank=True, max_length=135, verbose_name='出生地')),
                ('gender', models.CharField(blank=True, max_length=135, verbose_name='性别')),
                ('picture', models.ImageField(blank=True, upload_to='images/', verbose_name='個人照片')),
                ('attachment', models.FileField(blank=True, upload_to='file/', verbose_name='簡歷附件')),
                ('bachelor_school', models.CharField(blank=True, max_length=135, verbose_name='本科學校')),
                ('master_school', models.CharField(blank=True, max_length=135, verbose_name='研究生學校')),
                ('doctor_school', models.CharField(blank=True, max_length=135, verbose_name='博士生學校')),
                ('major', models.CharField(blank=True, max_length=135, verbose_name='專業')),
                ('degree', models.CharField(blank=True, choices=[('大學', '大學'), ('碩士', '碩士'), ('博士', '博士')], max_length=135, verbose_name='學歷')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='創建日期')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('candidate_introduction', models.TextField(blank=True, max_length=1024, verbose_name='自我介绍')),
                ('work_experience', models.TextField(blank=True, max_length=1024, verbose_name='工作經歷')),
                ('project_experience', models.TextField(blank=True, max_length=1024, verbose_name='项目經歷')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '簡歷',
                'verbose_name_plural': '簡歷列表',
            },
        ),
    ]
