# Generated by Django 3.1.5 on 2021-01-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210116_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='first_result',
            field=models.CharField(blank=True, choices=[('建議複試', '建議複試'), ('待定', '待定'), ('放棄', '放棄')], max_length=256, verbose_name='初試結果'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hr_result',
            field=models.CharField(blank=True, choices=[('建議錄用', '建議錄用'), ('待定', '待定'), ('放棄', '放棄')], max_length=256, verbose_name='HR複試結果'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_result',
            field=models.CharField(blank=True, choices=[('建議錄用', '建議錄用'), ('待定', '待定'), ('放棄', '放棄')], max_length=256, verbose_name='專業複試結果'),
        ),
    ]
